"""Knowledge platform primitives for OpenNICF."""

from .embeddings import (
    EmbeddingBackend,
    EmbeddingModelInfo,
    EmbeddingResult,
    EmbeddingBatchSizer,
    HashingEmbeddingBackend,
    LocalFirstEmbeddingService,
)
from .namespaces import IntegrationEdgeRecord, KnowledgeNamespaceRecord, build_namespace_record
from .models import (
    ArtifactRecord,
    AuditEvidenceRefRecord,
    AuditFindingRecord,
    AuditReportRecord,
    AuditTimelineEventRecord,
    ChunkRecord,
    EvidenceHit,
    EmbeddingRecord,
    IngestBundle,
    KnowledgeSource,
    KnowledgeSourceVersion,
    ParsedBlock,
    RetrievalEventRecord,
    RetrievalFilters,
    SearchCandidate,
    SourceKind,
    VerificationRequestRecord,
)
from .object_store import (
    FilesystemObjectStore,
    MemoryObjectStore,
    ObjectReference,
    ObjectStore,
)
from .retrieval import HybridRetriever, cosine_similarity
from .store import KnowledgePlatform, MemoryKnowledgeStore, PostgresKnowledgeStore

__all__ = [
    "ArtifactRecord",
    "AuditEvidenceRefRecord",
    "AuditFindingRecord",
    "AuditReportRecord",
    "AuditTimelineEventRecord",
    "ChunkRecord",
    "EmbeddingBackend",
    "EmbeddingBatchSizer",
    "EmbeddingModelInfo",
    "EmbeddingRecord",
    "EmbeddingResult",
    "IntegrationEdgeRecord",
    "EvidenceHit",
    "FilesystemObjectStore",
    "HashingEmbeddingBackend",
    "HybridRetriever",
    "IngestBundle",
    "KnowledgePlatform",
    "KnowledgeSource",
    "KnowledgeSourceVersion",
    "KnowledgeNamespaceRecord",
    "ParsedBlock",
    "LocalFirstEmbeddingService",
    "MemoryKnowledgeStore",
    "MemoryObjectStore",
    "ObjectReference",
    "ObjectStore",
    "PostgresKnowledgeStore",
    "RetrievalEventRecord",
    "RetrievalFilters",
    "SearchCandidate",
    "SourceKind",
    "VerificationRequestRecord",
    "build_namespace_record",
    "cosine_similarity",
]
