"""Knowledge platform primitives for OpenNICF."""

from .embeddings import (
    EmbeddingBackend,
    EmbeddingBatchSizer,
    EmbeddingError,
    EmbeddingMigration,
    EmbeddingModelInfo,
    EmbeddingResult,
    EmbeddingSpace,
    EmbeddingSpaceMismatch,
    GeminiEmbeddingBackend,
    HashingEmbeddingBackend,
    HttpEmbeddingBackend,
    LocalFirstEmbeddingService,
    PrivacyBoundaryError,
    QwenEmbeddingBackend,
)
from .admin import AdminOperation, KnowledgeAdministration, RetirementPolicy
from .models import (
    ArtifactRecord,
    AuditEvidenceRefRecord,
    AuditFindingRecord,
    AuditReportRecord,
    AuditTimelineEventRecord,
    ChunkRecord,
    EmbeddingRecord,
    EvidenceHit,
    IngestBundle,
    KnowledgeSource,
    KnowledgeSourceVersion,
    ParsedBlock,
    RetrievalEventRecord,
    RetrievalFilters,
    SearchCandidate,
    SourceKind,
    VerificationRequestRecord,
)
from .namespaces import (
    IntegrationEdgeRecord,
    KnowledgeNamespaceRecord,
    build_namespace_record,
)
from .object_store import (
    FilesystemObjectStore,
    MemoryObjectStore,
    ObjectReference,
    ObjectStore,
)
from .retrieval import HybridRetriever, cosine_similarity
from .store import KnowledgePlatform, MemoryKnowledgeStore, PostgresKnowledgeStore

__all__ = [
    "ArtifactRecord",
    "AdminOperation",
    "AuditEvidenceRefRecord",
    "AuditFindingRecord",
    "AuditReportRecord",
    "AuditTimelineEventRecord",
    "ChunkRecord",
    "EmbeddingBackend",
    "EmbeddingBatchSizer",
    "EmbeddingError",
    "EmbeddingMigration",
    "EmbeddingModelInfo",
    "EmbeddingRecord",
    "EmbeddingResult",
    "EmbeddingSpace",
    "EmbeddingSpaceMismatch",
    "EvidenceHit",
    "FilesystemObjectStore",
    "GeminiEmbeddingBackend",
    "HashingEmbeddingBackend",
    "HttpEmbeddingBackend",
    "HybridRetriever",
    "IngestBundle",
    "IntegrationEdgeRecord",
    "KnowledgeNamespaceRecord",
    "KnowledgePlatform",
    "KnowledgeAdministration",
    "KnowledgeSource",
    "KnowledgeSourceVersion",
    "LocalFirstEmbeddingService",
    "MemoryKnowledgeStore",
    "MemoryObjectStore",
    "ObjectReference",
    "ObjectStore",
    "ParsedBlock",
    "PostgresKnowledgeStore",
    "PrivacyBoundaryError",
    "QwenEmbeddingBackend",
    "RetrievalEventRecord",
    "RetrievalFilters",
    "RetirementPolicy",
    "SearchCandidate",
    "SourceKind",
    "VerificationRequestRecord",
    "build_namespace_record",
    "cosine_similarity",
]
